name: Build, Tag, and Push Docker Image to ACR

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-tag-push:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR via OIDC
        run: az acr login --name ${{ vars.REGISTRY_NAME }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ vars.REGISTRY_NAME }}.azurecr.io/dddadelaidewebsite:${{ github.sha }} .

      - name: Push the Docker image to ACR
        run: |
          docker push ${{ vars.REGISTRY_NAME }}.azurecr.io/dddadelaidewebsite:${{ github.sha }}

      - name: Determine Website Name
        id: set_website_name
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "::set-output name=website_name::dddadelaide-website"
          else
            echo "::set-output name=website_name::dddadelaide-website-test"
          fi

      - name: Deploy Website Revision
        uses: azure/container-apps-deploy-action@v2
        with:
          location: AustraliaEast
          containerAppName: ${{ steps.set_website_name.outputs.website_name }}
          imageToDeploy: dddadelaide.azurecr.io/dddadelaidewebsite:${{ github.sha }}
          targetPort: 3000
          ingress: external
          environmentVariables: >
            "one=two"
            "three=four"
          disableTelemetry: true